service: serverless-auction-house

custom:
  # Stage and region configuration
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}

  esbuild:
    platform: "node"
    target: node16
    sourcemap: linked
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs18.x
  memorySize: 128
  timeout: 10
  logRetentionInDays: 7
  logs:
    httpApi: true
  httpApi:
    cors: true

functions:
  app:
    handler: backend/src/handler.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  patterns:
    - "!**/*.test.ts"
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline

resources:
  Resources:
    # Users Table
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-users-
        AttributeDefinitions:
          - AttributeName: "user-id"
            AttributeType: "S"
          - AttributeName: "create-time"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "user-id"
            KeyType: "HASH"
          - AttributeName: "create-time"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    # Items Table
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-items
        AttributeDefinitions:
          - AttributeName: "item-id"
            AttributeType: "S"
          - AttributeName: "create-time"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "item-id"
            KeyType: "HASH"
          - AttributeName: "create-time"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST

    # Bids Table
    BidsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-bids
        AttributeDefinitions:
          - AttributeName: "bid-id"
            AttributeType: "S"
          - AttributeName: "create-time"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "bid-id"
            KeyType: "HASH"
          - AttributeName: "create-time"
            KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
