name: Discord Notification

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: SendDiscordNotification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            EVENT_TYPE="A new commit was pushed to the main branch"
            COMMIT_URL="${{ github.event.head_commit.url }}"
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          else
            EVENT_TYPE="A pull request was merged"
            COMMIT_URL="${{ github.event.pull_request.html_url }}"
            COMMIT_MESSAGE="${{ github.event.pull_request.title }}"
          fi
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"@everyone 🔥 **${EVENT_TYPE} by $GITHUB_ACTOR** 🔥\\n**Commit Message:** ${COMMIT_MESSAGE} \\n**Commit URL:** ${COMMIT_URL}\"}" \
          $DISCORD_WEBHOOK_URL
